[package]
name = "file-robot"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = "*"
users = "*"
notify = "6.1"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.47.1", features = ["rt", "macros", "time", "rt-multi-thread"] }
